### PR TITLE
Send the notification event callback

### PR DESCRIPTION
**Pull request by grrrian**
This allows receiving callbacks in the app when a push notification is received. 

When the app is running in foreground, the push payload is sent straight to the event callback defined in registerCallback(ecb, successCallback, errorCallback).

When the app is running in background, the push payload is handled by the native OS. Works for Android and iOS.

Also fixed:
- send push-open events to Parse Analytics
- initialize() method registers the device on iOS; this fixes the bug where calling getInstallationObjectId() could return null if you don't wait long enough after initializing + subscribing
- replace saveInBackground() with save() on Android when we are already on the background thread
- update the README

### CODE REVIEW

**Comment by avivais** [comment]
@grrrian, seems like there are conflicts, could you pull the latest code and resolve?

**Comment by grrrian** [comment]
Sure. Sorry about that

ian

**Comment by grrrian** [comment]
Alright, i tested it on Android an iOS. This should be good to go ;)

**Comment by nobesio** [comment]
When is this branch going to be merged? Thanks you very much

**Comment by jonathancod** [comment]
+1

**Comment by bluety** [comment]
+1

**Comment by garciadiegosebastian** [comment]
+1

**Comment by grrrian** [comment]
Can one of you test this from my branch (https://github.com/grrrian/phonegap-parse-plugin) to confirm it works? I only tested it on an iPhone 5 running iOS8 and on an Moto X running Android 4.4.2.

**Comment by jonathancod** [comment]
Greetings, i have been trying to use your branch but i got an error: "Cannot read property 'initialize' of undefined".
However i have to confess that i have no idea on how to do the part of the class in android.
Im using a moto g with android 4.4

**Comment by grrrian** [comment]
This happens because parsePlugin is undefined. You would get this error on any branch. Make sure to use parsePlugin once the device is ready (see README). parsePluign is a global variable, in angular you can access it like this:
<code>$window.parsePlugin</code>

**Comment by jonathancod** [comment]
That's the way i am doing it. And i got the same error on the avivais branch. The benjie one (https://github.com/benjie/phonegap-parse-plugin) however works fine, but i'm super interested in the callback events that you got here.

**Comment by grrrian** [comment]
Can you try again? There has been updates.

**Comment by grillorafael** [comment]
+1

**Comment by Gauloix** [comment]
Hi All !

Tried the grrrian branch and works perfect on IOS. But I have an error on Android (lolipop) on this line ParseInstallation.getCurrentInstallation().saveInBackground();

( The https://github.com/cookys/parse-push-plugin branch works great on lolipop, but not on iOs )

**Comment by grrrian** [comment]
@Gauloix : do you see bolts-android-1.1.4.jar in platforms/android/libs? Let's open an issue in my branch instead of discussing this here (https://github.com/grrrian/phonegap-parse-plugin/issues/2) ;)

**Comment by JeremyPlease** [comment]
+1

**Comment by rubnvp** [comment]
+1

**Comment by leonardliau** [comment]
I had successful working push notification. But I can't receive the push message using registerCallback.
When i test send push in parse.com and I click the app notification nothing happens.

Please help

**Comment by felquis** [comment]
@grrrian's repo looks like the best plugin to integrate Parse SDK with Cordova.

I'd appreciate if it was merged.

**Comment by grrrian** [comment]
Thanks!

ian

**Comment by felquis** [comment]
@grrrian We did have fun 6 years ago, thank you for all the support with this amazing plugin.

**Pull request closed without merging**
